risky: true

preset: symfony

enabled:
  - combine_consecutive_unsets
  - short_array_syntax
  - newline_after_open_tag
  - no_php4_constructor
  - no_useless_else
  - ordered_class_elements
  - ordered_use

finder:
  exclude:
    - 'Resources/skeleton'
    - 'Resources/public/vendor'
  not-path:
    - 'TagExpression/Lexer.php'
    - 'TagExpression/Parser.php'

